name: animals_v3
description: Animals and letters .

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  assets_audio_player: ^3.0.6
  google_mobile_ads: ^2.3.0
  flutter_launcher_icons: ^0.11.0
  wakelock: ^0.6.2

dev_dependencies:
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "images/logo.png"
  min_sdk_android: 21 

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - gifs/
    - audio1/
    - audio2/
